<?php
namespace Pushengage\Utils;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Constants {
	const NOTIFICATION_TITLE_MAX_LEN = 85;
	const NOTIFICATION_MESSAGE_MAX_LEN = 135;
	const NOTIFICATION_URL_MAX_LEN = 1600;
	const NOTIFICATION_SMALL_IMG_URL_MAX_LEN = 500;
	const NOTIFICATION_BIG_IMG_URL_MAX_LEN = 500;
	const NOTIFICATION_ACTION_LABEL_MAX_LEN = 12;
	const NOTIFICATION_ACTION_URL_MAX_LEN = 256;
	const NOTIFICATION_ACTION_IMG_URL_MAX_LEN = 256;
	const NOTIFICATION_UTM_SOURCE_MAX_LEN = 80;
	const NOTIFICATION_UTM_MEDIUM_MAX_LEN = 80;
	const NOTIFICATION_UTM_CAMPAIGN_MAX_LEN = 80;
	const NOTIFICATION_UTM_TERM_MAX_LEN = 80;
	const NOTIFICATION_UTM_CONTENT_MAX_LEN = 120;

}
