name: Foody Production Pipeline

on:
  push:
    branches:
      # - production
      - pipeline
      - 4-8-2023-fixes

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    env:
      TFVARSFILE: "terraform.tfvars"
      ENVOY_SERVER: "prod1"
      # ENVOY_BRANCH: "production"
      # ENVOY_BRANCH: "pipeline"
      ENVOY_BRANCH: "4-8-2023-fixes"
      ASG_NAME: "foody-autoscale-prod"
      ASG_DESIRED_CAPACITY: "5"
      ASG_MIN_SIZE: "5"
      ASG_MAX_SIZE: "30"
      AWS_INSTANCE_ID: "i-05da444bdd485d2b8" # same instance as ENVOY_SERVER, but instance ID instead of IP
      INSTANCE_TYPE: "t3.xlarge"
      KEY_NAME: "foody-prod" # key pair name for ASG
      SECURITY_GROUP_ID: "sg-03f4f895b2b9c9f2f"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP 7
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mysql, curl, gd, mbstring, xml, zip, intl, bcmath, iconv, exif, pcntl, pdo, pdo_mysql, mysqli, tokenizer, json, sockets, imagick

      - name: Reset Node.js
        run: rm -rf ~/mynvm

      - name: Install Old Node.js
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: v8.17.0

      - name: Install Python
        run: |
          sudo apt update
          sudo apt install -y python2
          python2 --version

      - name: .env Setup
        env:
          DB_HOST: ${{ vars.DB_HOST_PROD }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_USER: ${{ vars.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_PROD }}
        run: chmod +x .github/script/env_setup.sh && .github/script/env_setup.sh

      - name: SSH Keys
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_PROD }}
        run: chmod +x .github/script/create_ssh_config.sh && .github/script/create_ssh_config.sh

      - name: Envoy Setup
        run: composer global require laravel/envoy

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/download/1.10.20/composer.phar', 'composer.phar');"
          chmod +x composer.phar
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install project dependencies
        run: composer install

      - name: Install npm dependencies
        working-directory: web/app/themes/Foody
        run: |
          npm -v
          rm -rf node_modules
          rm package-lock.json
          npm install
          npm remove webpack webpack-cli node-sass
          npm install webpack@4.0.0 webpack-cli@2.1.3 node-sass@4.9.1
          npm rebuild node-sass 

      - name: Envoy deploy
        run: envoy run deploy --target=${{ env.ENVOY_SERVER }} --branch=${{ env.ENVOY_BRANCH }}

      - name: Reset Node.js
        run: rm -rf ~/mynvm

      - name: Install Node.js
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: stable

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Provider
        working-directory: .github/script/terraform
        env:
          BUCKET_NAME: ${{ vars.BUCKET_NAME }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          DYNAMODB_TABLE_NAME: ${{ vars.DYNAMODB_TABLE_NAME }}
          AWS_INSTANCE_ID: ${{ env.AWS_INSTANCE_ID }}
          INSTANCE_TYPE: ${{ env.INSTANCE_TYPE }}
          KEY_NAME: ${{ env.KEY_NAME }}
          SECURITY_GROUP_ID: ${{ env.SECURITY_GROUP_ID }}
          ASG_NAME: ${{ env.ASG_NAME }}
          TF_STATE_KEY: ${{ vars.TF_STATE_KEY_STAGING }}
          ASG_DESIRED_CAPACITY: ${{ env.ASG_DESIRED_CAPACITY }}
          ASG_MIN_SIZE: ${{ env.ASG_MIN_SIZE }}
          ASG_MAX_SIZE: ${{ env.ASG_MAX_SIZE }}
        run: |
          chmod +x ../terraform_provider.sh && ../terraform_provider.sh
          chmod +x ../create_tfvars.sh && ../create_tfvars.sh

      - name: Terraform Init
        working-directory: .github/script/terraform
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: terraform init
          
      - name: Terraform Import
        working-directory: .github/script/terraform
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: terraform import aws_autoscaling_group.main ${{ env.ASG_NAME }} || true

      - name: Terraform Plan
        working-directory: .github/script/terraform
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: terraform plan -out=tfplan -var-file=${{ env.TFVARSFILE }}

      - name: Terraform Apply
        working-directory: .github/script/terraform
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: terraform apply -auto-approve tfplan
