<?php
/** Enable W3 Total Cache */
define('WP_CACHE', true); // Added by W3 Total Cache






/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
/* Multisite */
if($_SERVER['SERVER_NAME'] == 'staging.foody.co.il'){
    define('DB_HOST', '127.0.0.1:3306');
} 

require_once(dirname(__DIR__) . '/vendor/autoload.php');
require_once(dirname(__DIR__) . '/config/application.php');
require_once(ABSPATH . 'wp-settings.php');
/** Define aksimet API Key */
define('WPCOM_API_KEY','63b942b7c4e1');